stages:
  - stage : Continuous_Integration
    jobs :
     - job : build
       steps:
       - script : dotnet restore
         displayname : Restore package
       - script : dotnet build
       - script : dotnet run
         displayname : Run the application
     - job : test 
       steps :
       - script : dotnet build
       - script : dotnet test 