stages:
  - stage : Continuous_Integration
    jobs :
     - job : build
       steps:
       - script : dotnet restore
       - script : dotnet build
     - job : test 
       steps :
       - script : dotnet build
       - script : dotnet test 